server.port=8083
spring.application.name=compraventa
spring.main.banner-mode=off

spring.data.mongodb.uri=mongodb://localhost:27018/compraventas
spring.data.mongodb.database=compraventas

servicios.usuarios.url=http://localhost:8081/
servicios.productos.url=http://localhost:8082/

logging.level.es.um.arso.compraventa=DEBUG
